Bug : Need to import time ?
Traceback (most recent call last):
  File "qtum_monitor.py", line 102, in <module>
    latest_data['last_block_time_won'] = int(time.time())
NameError: name 'time' is not defined